<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '#' => '#',
    'All emergents' => 'Todos los emergentes',
    'Avg. conc. gap' => 'Brecha conc. promedio',
    'Avg. mon. prod.' => 'Prod. mono. promedio',
    'Competence Matrix' => 'Matriz de competencias',
    'Cons. gap' => 'Brecha de con.',
    'Consciouness Ranking' => 'Ranking de conciencia',
    'Consciousness' => 'Conciencia',
    'Consciousness and Responsability Matrix' => 'Matriz de consciencia y responsabilidad',
    'Consciousness gap emergents' => 'Emergentes por brecha de conciencia',
    'Dashboard' => 'Tablero',
    'Emergent Matrix' => 'Matriz de emergentes',
    'Group Competence Matrix' => 'Matriz de competencias grupales',
    'Group Consciousness and Responsability Matrix' => 'Matriz de conciencia y responsabilidad grupal',
    'Group Emergents Matrix' => 'Matriz de emergentes grupales',
    'Group Perception Adjustment Matrix' => 'Matriz de ajuste perceptual grupal',
    'Group Perception Matrix' => 'Matriz de percepción grupal',
    'Group Performance Matrix' => 'Matriz de desempeño grupal',
    'Group Rankings' => 'Rankings grupales',
    'Group Relations Matrix' => 'Matriz de relaciones grupales',
    'How I see me' => 'Como me veo',
    'How they see me' => 'Como me ven',
    'Individual Competence Matrix' => 'Matriz de competencias individuales',
    'Individual Consciousness and Responsability Matrix' => 'Matriz de conciencia y responsabilidad individual',
    'Individual Emergents Matrix' => 'Matriz de emergentes individuales',
    'Individual Perception Adjustment Matrix' => 'Matriz de ajuste perceptual individual',
    'Individual Performance Matrix' => 'Matriz de desempeño individual',
    'Individual Rankings' => 'Rankings individuales',
    'Individual Relations Matrix' => 'Matriz de relaciones individuales',
    'Individual Wheel' => 'Rueda individual',
    'Individual projection toward the group' => 'Proyección individual hacia el grupo',
    'Individual projection toward the organization' => 'Proyección individual hacia la organización',
    'M. Productivity' => 'Productividad M.',
    'Monofactorial productivity' => 'Productividad monofactorial',
    'Organiz. Emergents Matrix' => 'Matriz de emergentes organiz.',
    'Organizational Competence Matrix' => 'Matriz de competencias organizacionales',
    'Organizational Consciousness and Responsability Matrix' => 'Matriz de conciencia y responsabilidad organizacional',
    'Organizational Emergents Matrix' => 'Matriz de emergentes organizacionales',
    'Organizational Perception Adjustment Matrix' => 'Matriz de ajuste perceptual organizacional',
    'Organizational Perception Matrix' => 'Matriz de percepcion organizacional',
    'Organizational Performance Matrix' => 'Matriz de desempeño organizacional',
    'Organizational Rankings' => 'Rankings organizacionales',
    'Organizational Relations Matrix' => 'Matriz de relaciones organizacionales',
    'Perception Adjustment Matrix' => 'Matriz de ajuste perceptual',
    'Performance Matrix' => 'Matriz de performance',
    'Person' => 'Persona',
    'Prod. deviation' => 'Desviación de prod.',
    'Prod. x Cons. Ranking' => 'Ranking prod. x conc.',
    'Productivity Ranking' => 'Ranking de productividad',
    'Ranking' => 'Ranking',
    'Relation Matrix' => 'Matriz de relaciones',
    'Responsability' => 'Responsabilidad',
    'Select assesment ...' => 'Elija relevamiento ...',
    'Select company ...' => 'Elija empresa ...',
    'Select member ...' => 'Elija miembro ...',
    'Select team ...' => 'Elija equipo ...',
    'Select wheel type ...' => 'Elija tipo de rueda ...',
    'Show' => 'Mostrar',
    'St. dev.' => 'Desv. est.',
    'Strengths' => 'Fortalezas',
    'Value' => 'Valor',
    'Weaknesses' => 'Debilidades',
];
