<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action Plan' => 'Plan de acción',
    'Analysis' => 'Análisis',
    'Analysis saved.' => 'Análisis guardado.',
    'Competence Matrix' => 'Matriz de competencias',
    'Competences Matrix' => 'Matriz de competencias',
    'Competences Matrix of {member}' => 'Matriz de competencias de {member}',
    'Conclusions - Stage 1' => 'Conclusiones - Fase 1',
    'Effectiveness Matrix' => 'Matriz de efectividad',
    'Emergent Matrix' => 'Matriz de emergentes',
    'Emergents Matrix' => 'Matriz de emergentes',
    'Emergents Matrix of {member}' => 'Matriz de emergentes de {member}',
    'Fundaments' => 'Fundamentos',
    'Group and Organizational Analysis' => 'Análisis grupal y organizacional',
    'Index' => 'Índice',
    'Individual Analysis' => 'Análisis Individual',
    'Introduction' => 'Introducción',
    'Keywords' => 'Palabras clave',
    'Natural Team' => 'Equipo natural',
    'Perception Matrix' => 'Matriz de percepción',
    'Perception Matrix of {member}' => 'Matriz de percepción de {member}',
    'Performance Matrix' => 'Matriz de desempeño',
    'Performance Matrix of {member}' => 'Matriz de desempeño de {member}',
    'Relations Matrix' => 'Matriz de relaciones',
    'Relations Matrix of {member}' => 'Matriz de relaciones de {member}',
    'Report' => 'Informe',
    'Since graphic clarity, farther analisis is not required' => 'Dada la claridad de los gráficos, un análisis adicional no es requerido.',
    'Summary' => 'Síntesis',
];
