<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add licences' => 'Agregar licencias',
    'Amount' => 'Monto',
    'Available licences' => 'Licencias disponibles',
    'Begin payment' => 'Comenzar pago',
    'Buy Licences' => 'Comprar licencias',
    'Consumed' => 'Consumido',
    'Consumer' => 'Consumidor',
    'Created' => 'Creado',
    'Dear administrator, I\'m requesting {q} licences. Thanks.' => 'Estimado administrador, estoy solicitando {q} licencias. Gracias.',
    'Edit Licence Type' => 'Editar tipo de licencia',
    'Email required to send link' => 'Correo electrónica requerido para enviar link',
    'Get invoice' => 'Descargar factura',
    'Go to Invoice' => 'Ir a factura',
    'Go to My Licences' => 'Ir a Mis licencias',
    'Licence Type' => 'Tipo de licencia',
    'Licence Types' => 'Tipos de licencias',
    'Licences' => 'Licencias',
    'Licences required' => 'Licencias requeridas',
    'Local Amount' => 'Monto local',
    'My Licences' => 'Mis licencias',
    'New Licence Type' => 'Nuevo tipo de licencia',
    'Not available licences' => 'Licencias no disponibles',
    'Payed' => 'Pagado',
    'Price' => 'Precio',
    'Price in USD $' => 'Precio es USD $',
    'Product' => 'Producto',
    'Quantity' => 'Cantidad',
    'Quantity to buy' => 'Cantidad a comprar',
    'Remove licences' => 'Quitar licencias',
    'Requesting licences' => 'Solicitando licencias',
    'Send payment link' => 'Enviar link de pago',
    'Sent payment link to this email' => 'Enviar link de pago a este correo electrónico',
    'Stock quantity not available' => 'Cantidad en stock no disponible',
    'Total' => 'Total',
    'VACH licences payment link' => '',
    'You need {count} more licences' => 'Necesita {count} licencias más',
    'Your balance' => 'Su saldo',
    'Your balance of {licence type}' => 'Su saldo de {licence type}',
    'consumed' => 'consumido',
];
